name: Academy API Robot
on: push
jobs:
  test:
    name: Testes de API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://github.com/QualityEagles2024/eagles-academy-api-robot.git
    steps:
      - name: Clonando para o repositório na máquina virtual
        uses: actions/checkout@v4

      - name: Listar Arquivos e Pastas
        run: ls -R

      - name: Instalação da versão 3.12 do Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Criar Ambiente Virtual (venv)
        run: python -m venv venv

      - name: Ativar venv e Instalar Dependências
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Executar Testes de API do Robot
        run: |
          source venv/bin/activate
          robot --outputdir results/ tests/

      - name: Salvar o Report dos Testes
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-${{ github.run_number }}-${{ github.run_id }} # Nome único para o artefato
          path: results/
          if-no-files-found: warn # Prevenir erro caso o artefato já exista

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: results/
          name: github-pages-${{ github.run_number }}-${{ github.run_id }} # Nome único para garantir que seja o mesmo

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.run_number }}-${{ github.run_id }} # Garantindo o uso do mesmo nome do artefato
